#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: gitlab-ci
#  namespace: ops
#---
#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  namespace: ops
#  name: gitlab-ci
#rules:
#  - apiGroups: [""]
#    resources: ["*"]
#    verbs: ["*"]
#  - apiGroups: ["apps"]
#    resources: ["*"]
#    verbs: ["*"]
#  - apiGroups: ["batch"]
#    resources: ["*"]
#    verbs: ["*"]
#  - apiGroups: ["extensions"]
#    resources: ["*"]
#    verbs: ["*"]
#  - apiGroups: ["autoscaling"]
#    resources: ["*"]
#    verbs: ["*"]
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: gitlab-ci
#  namespace: ops
#subjects:
#  - kind: ServiceAccount
#    name: gitlab-ci
#    namespace: ops
#roleRef:
#  kind: Role
#  name: gitlab-ci
#  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: gitlab

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab
  namespace: ops
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
